#!/bin/zsh

set -euo pipefail

bin_install_root="${HOME}/.bin"

latest_yarn_install_url=$(curl \
  --location \
  --silent \
  --max-redirs 1 \
  --write-out %{url_effective} \
  --output /dev/null \
  https://yarnpkg.com/latest.tar.gz || echo)

if [ -z "${latest_yarn_install_url}" ]; then
  echo "✘ could not determine latest yarn version" >&2
  exit 1
fi

latest_yarn_install_filename=$(basename "${latest_yarn_install_url}" .tar.gz)
latest_yarn_version=${latest_yarn_install_filename#yarn-v}

scripts_directory=${0:a:h}

"${scripts_directory}/install-package" \
  yarn \
  "${latest_yarn_version}" \
  "${latest_yarn_install_url}"

"${scripts_directory}/alias-package" \
  yarn \
  "${latest_yarn_version}" \
  latest
