#!/bin/zsh

set -euo pipefail

version=
set_lts=false
architecture=

while [ $# -gt 0 ]; do
  case "${1}" in
    -h|--help)
      echo "usage: install-node [--lts] <version>"
      echo
      echo "Installs Node.js with the specified <version> and optionally aliases"
      echo "it to 'lts' given the '--lts' flag."
      exit 0
      ;;

    --lts)
      set_lts=true
      ;;

    -*)
      echo "✘ unexpected argument: ${1}" >&2
      exit 1
      ;;

    *)
      if [ -n "${version}" ]; then
        echo "✘ unexpected argument after version: ${1}" >&2
        exit 1
      fi
      version="${1}"
      ;;
  esac

  shift
done

if [ -z "${version}" ]; then
  echo "✘ missing version" >&2
  exit 1
fi

if [ "$(uname)" = "Darwin" ]; then
  architecture="darwin-x64"
else
  architecture="linux-x64"
fi

tarball_url="https://nodejs.org/dist/v${version}/node-v${version}-${architecture}.tar.gz"

scripts_directory="${0:a:h}"
"${scripts_directory}/install-package" \
  node \
  "${version}" \
  "${tarball_url}"

if [ "$("${HOME}/.bin/node/${version}/bin/node" -v 2>/dev/null)" != "v${version}" ]; then
  echo "✘ verification of node ${version} failed" >&2
  exit 1
fi

if [ "${set_lts}" = "true" ]; then
  "${scripts_directory}/alias-package" \
    node \
    "${version}" \
    lts
fi
