#!/bin/zsh

set -euo pipefail

cmd=$(basename "${0}")
package=${1:-}
version=${2:-}
tarball_url=${3:-}

if [ -z "${package}" ]; then
  echo "✘ missing package" >&2
  exit 1
fi

if [ -z "${version}" ]; then
  echo "✘ missing version" >&2
  exit 1
fi

bin_install_root="${HOME}/.bin"
bin_install_target="${bin_install_root}/${package}/${version}"

if [ "${cmd}" = "install-package" ]; then
  if [ -z "${tarball_url}" ]; then
    echo "✘ missing url" >&2
    exit 1
  fi

  if [ -d "${bin_install_target}" ]; then
    echo "✓ ${package} ${version} already installed at ${bin_install_target}"
  else
    echo "📦 installing ${package} ${version} at ${bin_install_target}"
    tmp_install_target=$(mktemp -d -t install-package.XXXXX)
    curl \
      --silent \
      --location \
      --output - \
      "${tarball_url}" \
    | tar xz --strip-components 1 -C "${tmp_install_target}"
    mkdir -p "$(dirname "${bin_install_target}")"
    mv "${tmp_install_target}" "${bin_install_target}"
    echo "✓ ${package} ${version} installed at ${bin_install_target}"
  fi
elif [ "${cmd}" = "uninstall-package" ]; then
  if [ -d "${bin_install_target}" ]; then
    rm -rf "${bin_install_target}"
    echo "✓ ${package} ${version} uninstalled from ${bin_install_target}"
  else
    echo "✓ ${package} ${version} was not found at ${bin_install_target}, nothing to do"
  fi
else
  echo "✘ unknown command name: ${cmd}" >&2
  exit 1
fi
